### ISSUE TITLE
Calibration? Pointcloud fusion after capture?

### ISSUE THREAD

**Issue by jessekirbs** [n1ckfg/opencv-kinfu#1]
Hello,

I have a couple questions about this software that I can't find the answers to.

Can this be used with multiple Kinects for Azure?
Does this software handle the calibration of the Kinects? I don't quite understand what it means by 'how to feed calibration'.
Can this software be used to merge and mesh pointclouds that have been previously recorded? Or is it only realtime?

Thank you!

**Comment by n1ckfg** [comment]
Afaik the answer is no to all, this is just the stock example from the SDK with the necessary libraries precompiled. There are open multi-camera projects brewing, although I haven't tried any--for instance https://github.com/VCL3D/VolumetricCapture

**Comment by jessekirbs** [comment]
> 
> 
> Afaik the answer is no to all, this is just the stock example from the SDK with the necessary libraries precompiled. There are open multi-camera projects brewing, although I haven't tried any--for instance https://github.com/VCL3D/VolumetricCapture

Thanks for the response, @n1ckfg!
