### ISSUE TITLE
I encountered an error when running kinfu_example.exe

### ISSUE THREAD

**Issue by holydawn96** [n1ckfg/opencv-kinfu#2]
I encountered an error when running kinfu_example.exe for debug configuration: OpenCL: Kernel(fillPtsNrm)::set(arg_index=14, flags=260): can't create cl_mem handle for passed UMat buffer (addr=000000E52C34D410)
Do you have any solution ?

![1111111111](https://user-images.githubusercontent.com/33420827/120667957-935c5980-c4c0-11eb-8442-f2920570f85b.png)

**Comment by n1ckfg** [comment]
The first place to look with Azure Kinect is USB issues; are other apps working with your camera? Also, are you on Win10 with Nvidia Studio drivers?

**Comment by adahbingee** [comment]
Similar error, too
```
OpenCL error CL_OUT_OF_RESOURCES (-5) during call: clEnqueueNDRangeKernel('fillPtsNrm', dims=3, globalsize=512x512x512, localsize=8x8x16) sync=true
```

**Comment by n1ckfg** [comment]
Works for me; have you installed the Azure Kinect SDK? If there's a newer version out I might need to recompile.

**Comment by adahbingee** [comment]
Found the problem. I unplugged all HDMI from my graphics cards, then just use integrated Intel GPU.
It was good to run with Intel's GPU.
Nvidia's GPU support OpenCL not very well. 
My card is RTX 2060

**Comment by n1ckfg** [comment]
Thanks for coming back with a solution!
